DROP TABLE IF EXISTS `product_categories`;
DROP TABLE IF EXISTS `product_comments`;
DROP TABLE IF EXISTS `product_custom_field_datas`;
DROP TABLE IF EXISTS `product_custom_fields`;
DROP TABLE IF EXISTS `product_media_categories`;
DROP TABLE IF EXISTS `product_medias`;
DROP TABLE IF EXISTS `product_prices`;
DROP TABLE IF EXISTS `product_promotions`;
DROP TABLE IF EXISTS `products`;